import { createFileRoute } from "@tanstack/react-router";
import { Link } from "@tanstack/react-router";

export const Route = createFileRoute("/_legal/policy")({
  component: RouteComponent,
});

function RouteComponent() {
  return (
    <article className="space-y-8 text-sm leading-relaxed">
      <div className="space-y-2">
        <h1 className="font-semibold text-3xl tracking-tight">Privacy Policy</h1>
        <p className="text-muted-foreground">Last updated: April 18, 2026</p>
      </div>

      <p>
        Floos (&quot;us&quot;, &quot;we&quot;, or &quot;our&quot;) operates the Floos application
        (the &quot;Service&quot;).
      </p>
      <p>
        This page describes our policies regarding the collection, use, and disclosure of personal
        data when you use the Service and the choices you have associated with that data. Unless
        otherwise defined in this Privacy Policy, terms used here have the same meanings as in our{" "}
        <Link className="font-medium text-primary underline underline-offset-4" to="/terms">
          Terms of Service
        </Link>
        .
      </p>
      <p>
        We use your data to provide and improve the Service. By using the Service, you agree to the
        collection and use of information in accordance with this policy.
      </p>

      <section className="space-y-3">
        <h2 className="font-semibold text-lg">Definitions</h2>
        <dl className="space-y-4">
          <div>
            <dt className="font-medium">Service</dt>
            <dd className="text-muted-foreground">The Floos application operated by us.</dd>
          </div>
          <div>
            <dt className="font-medium">Personal data</dt>
            <dd className="text-muted-foreground">
              Data about a living individual who can be identified from those data (or from those
              and other information either in our possession or likely to come into our possession).
            </dd>
          </div>
          <div>
            <dt className="font-medium">Usage data</dt>
            <dd className="text-muted-foreground">
              Data collected automatically, either generated by the use of the Service or from the
              Service infrastructure (for example, the duration of a page visit).
            </dd>
          </div>
          <div>
            <dt className="font-medium">Cookies</dt>
            <dd className="text-muted-foreground">
              Small files stored on your device (computer or mobile device).
            </dd>
          </div>
          <div>
            <dt className="font-medium">Data controller</dt>
            <dd className="text-muted-foreground">
              For the purpose of this Privacy Policy, we are the data controller of your personal
              data.
            </dd>
          </div>
          <div>
            <dt className="font-medium">Data processors (or service providers)</dt>
            <dd className="text-muted-foreground">
              Any natural or legal person who processes the data on behalf of the data controller.
              We may use the services of various service providers to process your data more
              effectively.
            </dd>
          </div>
          <div>
            <dt className="font-medium">Data subject (or user)</dt>
            <dd className="text-muted-foreground">
              Any living individual who is using the Service and is the subject of personal data.
            </dd>
          </div>
        </dl>
      </section>

      <section className="space-y-3">
        <h2 className="font-semibold text-lg">Information collection and use</h2>
        <p>
          We collect several types of information for various purposes to provide and improve the
          Service to you.
        </p>

        <h3 className="font-medium">Types of data collected</h3>

        <h4 className="font-medium text-foreground text-sm">Personal data</h4>
        <p>
          While using our Service, we may ask you to provide certain personally identifiable
          information that can be used to contact or identify you. Personally identifiable
          information may include, but is not limited to:
        </p>
        <ul className="list-disc space-y-1 pl-6">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Cookies and usage data</li>
        </ul>
        <p>
          We may use your personal data to contact you with newsletters, marketing or promotional
          materials, and other information that may be of interest to you. You may opt out of
          receiving any, or all, of these communications from us by following the unsubscribe link
          or the instructions provided in any email we send.
        </p>

        <h4 className="font-medium text-foreground text-sm">Usage data</h4>
        <p>
          When you access the Service, we may collect certain information automatically, including,
          but not limited to, the type of device you use, your device unique ID, the IP address of
          your device, your operating system, the type of Internet browser you use, unique device
          identifiers, and other diagnostic data.
        </p>

        <h4 className="font-medium text-foreground text-sm">Tracking and cookies data</h4>
        <p>
          We use cookies and similar tracking technologies to track activity on our Service and hold
          certain information.
        </p>
        <p>
          Cookies are files with a small amount of data which may include an anonymous unique
          identifier. Cookies are sent to your browser from a website and stored on your device.
          Other tracking technologies are also used such as beacons, tags, and scripts to collect
          and track information and to improve and analyze our Service.
        </p>
        <p>
          You can instruct your browser to refuse all cookies or to indicate when a cookie is being
          sent. However, if you do not accept cookies, you may not be able to use some portions of
          our Service.
        </p>
        <p>Examples of cookies we may use:</p>
        <ul className="list-disc space-y-1 pl-6">
          <li>
            <span className="font-medium">Session cookies</span> to operate our Service.
          </li>
          <li>
            <span className="font-medium">Preference cookies</span> to remember your preferences and
            various settings.
          </li>
          <li>
            <span className="font-medium">Security cookies</span> for security purposes.
          </li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="font-semibold text-lg">Use of data</h2>
        <p>Floos uses the collected data for various purposes:</p>
        <ul className="list-disc space-y-1 pl-6">
          <li>To provide and maintain our Service</li>
          <li>To notify you about changes to our Service</li>
          <li>
            To allow you to participate in interactive features of our Service when you choose to do
            so
          </li>
          <li>To provide customer support</li>
          <li>To gather analysis or valuable information so that we can improve our Service</li>
          <li>To monitor the usage of our Service</li>
          <li>To detect, prevent, and address technical issues</li>
          <li>
            To provide you with news, special offers, and general information about other goods,
            services, and events which we offer that are similar to those that you have already
            purchased or enquired about unless you have opted not to receive such information
          </li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="font-semibold text-lg">Legal basis for processing (GDPR)</h2>
        <p>
          If you are from the European Economic Area (EEA), our legal basis for collecting and using
          the personal information described in this Privacy Policy depends on the personal data we
          collect and the specific context in which we collect it.
        </p>
        <p>We may process your personal data because:</p>
        <ul className="list-disc space-y-1 pl-6">
          <li>We need to perform a contract with you</li>
          <li>You have given us permission to do so</li>
          <li>
            The processing is in our legitimate interests and it is not overridden by your rights
          </li>
          <li>For payment processing purposes</li>
          <li>To comply with the law</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="font-semibold text-lg">Retention of data</h2>
        <p>
          We will retain your personal data only for as long as is necessary for the purposes set
          out in this Privacy Policy. We will retain and use your personal data to the extent
          necessary to comply with our legal obligations (for example, if we are required to retain
          your data to comply with applicable laws), resolve disputes, and enforce our legal
          agreements and policies.
        </p>
        <p>
          We will also retain usage data for internal analysis purposes. Usage data is generally
          retained for a shorter period of time, except when this data is used to strengthen the
          security or to improve the functionality of our Service, or we are legally obligated to
          retain this data for longer periods.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-semibold text-lg">Transfer of data</h2>
        <p>
          Your information, including personal data, may be transferred to—and maintained
          on—computers located outside of your state, province, country, or other governmental
          jurisdiction where the data protection laws may differ from those of your jurisdiction.
        </p>
        <p>
          If you are located outside Sweden and choose to provide information to us, please note
          that we may transfer the data, including personal data, to Sweden and process it there.
        </p>
        <p>
          Your consent to this Privacy Policy followed by your submission of such information
          represents your agreement to that transfer.
        </p>
        <p>
          We will take all steps reasonably necessary to ensure that your data is treated securely
          and in accordance with this Privacy Policy and no transfer of your personal data will take
          place to an organization or a country unless there are adequate controls in place
          including the security of your data and other personal information.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-semibold text-lg">Disclosure of data</h2>

        <h3 className="font-medium">Business transaction</h3>
        <p>
          If we are involved in a merger, acquisition, or asset sale, your personal data may be
          transferred. We will provide notice before your personal data is transferred and becomes
          subject to a different privacy policy.
        </p>

        <h3 className="font-medium">Disclosure for law enforcement</h3>
        <p>
          Under certain circumstances, we may be required to disclose your personal data if required
          to do so by law or in response to valid requests by public authorities (for example, a
          court or a government agency).
        </p>

        <h3 className="font-medium">Legal requirements</h3>
        <p>
          We may disclose your personal data in the good faith belief that such action is necessary
          to:
        </p>
        <ul className="list-disc space-y-1 pl-6">
          <li>Comply with a legal obligation</li>
          <li>Protect and defend our rights or property</li>
          <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
          <li>Protect the personal safety of users of the Service or the public</li>
          <li>Protect against legal liability</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="font-semibold text-lg">Security of data</h2>
        <p>
          The security of your data is important to us, but remember that no method of transmission
          over the Internet or method of electronic storage is 100% secure. While we strive to use
          commercially acceptable means to protect your personal data, we cannot guarantee its
          absolute security.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-semibold text-lg">&quot;Do not track&quot; signals (CalOPPA)</h2>
        <p>
          We do not support Do Not Track (&quot;DNT&quot;). Do Not Track is a preference you can set
          in your web browser to inform websites that you do not want to be tracked.
        </p>
        <p>
          You can enable or disable Do Not Track by visiting the preferences or settings page of
          your web browser.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-semibold text-lg">Your data protection rights (GDPR)</h2>
        <p>
          If you are a resident of the European Economic Area (EEA), you have certain data
          protection rights. We aim to take reasonable steps to allow you to correct, amend, delete,
          or limit the use of your personal data.
        </p>
        <p>
          If you wish to be informed about what personal data we hold about you and if you want it
          to be removed from our systems, please contact us.
        </p>
        <p>In certain circumstances, you have the following rights:</p>
        <ul className="list-disc space-y-1 pl-6">
          <li>
            <span className="font-medium">The right to access, update, or delete</span> the
            information we have on you. Whenever made possible, you can access, update, or request
            deletion of your personal data directly within your account settings section. If you are
            unable to perform these actions yourself, please contact us to assist you.
          </li>
          <li>
            <span className="font-medium">The right of rectification.</span> You have the right to
            have your information rectified if that information is inaccurate or incomplete.
          </li>
          <li>
            <span className="font-medium">The right to object.</span> You have the right to object
            to our processing of your personal data.
          </li>
          <li>
            <span className="font-medium">The right of restriction.</span> You have the right to
            request that we restrict the processing of your personal information.
          </li>
          <li>
            <span className="font-medium">The right to data portability.</span> You have the right
            to be provided with a copy of the information we have on you in a structured,
            machine-readable, and commonly used format.
          </li>
          <li>
            <span className="font-medium">The right to withdraw consent.</span> You also have the
            right to withdraw your consent at any time where we relied on your consent to process
            your personal information.
          </li>
        </ul>
        <p>
          Please note that we may ask you to verify your identity before responding to such
          requests.
        </p>
        <p>
          You have the right to complain to a data protection authority about our collection and use
          of your personal data. For more information, please contact your local data protection
          authority in the European Economic Area (EEA).
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-semibold text-lg">Service providers</h2>
        <p>
          We may employ third-party companies and individuals to facilitate our Service
          (&quot;Service Providers&quot;), provide the Service on our behalf, perform
          Service-related services, or assist us in analyzing how our Service is used.
        </p>
        <p>
          These third parties have access to your personal data only to perform these tasks on our
          behalf and are obligated not to disclose or use it for any other purpose.
        </p>

        <h3 className="font-medium">Analytics</h3>
        <p>
          We may use third-party service providers to monitor and analyze the use of our Service.
          Those providers are subject to their own privacy policies; we encourage you to review
          them.
        </p>

        <h3 className="font-medium">Payments</h3>
        <p>
          We may provide paid products and/or services within the Service. In that case, we use
          third-party services for payment processing.
        </p>
        <p>
          We will not store or collect your payment card details. That information is provided
          directly to our third-party payment processors whose use of your personal information is
          governed by their privacy policies. PCI-DSS requirements help ensure the secure handling
          of payment information.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-semibold text-lg">Links to other sites</h2>
        <p>
          Our Service may contain links to other sites that are not operated by us. If you click a
          third-party link, you will be directed to that third party&apos;s site. We strongly advise
          you to review the privacy policy of every site you visit.
        </p>
        <p>
          We have no control over and assume no responsibility for the content, privacy policies, or
          practices of any third-party sites or services.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-semibold text-lg">Children&apos;s privacy</h2>
        <p>Our Service does not address anyone under the age of 18 (&quot;Children&quot;).</p>
        <p>
          We do not knowingly collect personally identifiable information from anyone under the age
          of 18. If you are a parent or guardian and you are aware that your child has provided us
          with personal data, please contact us. If we become aware that we have collected personal
          data from children without verification of parental consent, we take steps to remove that
          information from our servers.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-semibold text-lg">Changes to this privacy policy</h2>
        <p>
          We may update our Privacy Policy from time to time. We will notify you of any changes by
          posting the new Privacy Policy on this page.
        </p>
        <p>
          We will let you know via email and/or a prominent notice on our Service, prior to the
          change becoming effective and update the &quot;last updated&quot; date at the top of this
          Privacy Policy.
        </p>
        <p>
          You are advised to review this Privacy Policy periodically for any changes. Changes to
          this Privacy Policy are effective when they are posted on this page.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-semibold text-lg">Contact us</h2>
        <p>If you have any questions about this Privacy Policy, please contact us:</p>
        <p>
          By email:{" "}
          <a
            className="font-medium text-primary underline underline-offset-4"
            href="mailto:legal@floos.app"
          >
            legal@floos.app
          </a>
        </p>
      </section>
    </article>
  );
}
